name: Generate Profile Card

on:
  schedule:
    # Run everyday at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Generate Card
        uses: ./ # Uses the action defined in the root using action.yml
        with:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          THEME: "tokyonight"
          OUTPUT_PATH: "profile-card.svg"

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add profile-card.svg
          git commit -m "Update profile card" || exit 0
          git push
